ombulabs/blog

_posts/2015-01-19-enumerator-grep-vs-enumerator-select.markdown
_posts/2015-04-09-enumerator-grep-vs-enumerator-select.markdown

Hey @etagwerker, 
This PR adds a post about `Enumerable#grep` vs `Enumerable#select`. 
Please check it out and let me know what you think, thanks!

Added post about Enumerable#grep vs Enumerable#select.

---

_posts/2015-06-28-how-to-git-push-with-blocked-ports.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/git/github/how-to-git-push-with-blocked-ports.html
_site/index.html
_site/rss.xml
_site/tags/git/index.html
_site/tags/github/index.html

Hey @mauro-oto @alanhala, 
I added a short post about pushing via https. 
Please check it out and let me know.
Thanks!

How to get around blocked ports to git push

---

_posts/2015-06-30-the-lean-startup-way.markdown
_site/authors/etagwerker/index.html
_site/index.html
_site/lean startup/the-lean-startup-way.html
_site/rss.xml
_site/tags/lean-startup/index.html

Hey @mauro-oto @cecilia-ombulabs @alanhala, 
I added an article about our way to apply the lean startup methodology to our clients. 
Please check it out and let me know if you have any feedback.
Thanks!

Apply lean startup to client projects

---

_config.yml
_includes/disqus.html
_layouts/post.html
_plugins/environment_variables.rb
_site/about.html
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/git/github/4-useful-github-tricks.html
_site/git/github/how-to-git-push-with-blocked-ports.html
_site/index.html
_site/lean startup/the-lean-startup-way.html
_site/ruby/benchmark/enumerator-grep-vs-enumerator-select.html
_site/software development/software quality/our-definition-of-done.html
_site/tags/benchmark/index.html
_site/tags/git/index.html
_site/tags/github/index.html
_site/tags/lean-startup/index.html
_site/tags/ruby/index.html
_site/tags/software-development/index.html
_site/tags/software-quality/index.html

Hey @mauro-oto,
This PR fixes the disqus and GA integration.
Thanks!

Fix disqus google analytics integration

---

_includes/post_excerpt.html
_layouts/author_index.html
_layouts/category_index.html
_plugins/environment_variables.rb
_posts/2015-07-14-mercado-pago-security-vulnerability.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/index.html
_site/rss.xml
_site/security/mercado-pago-security-vulnerability.html
_site/tags/benchmark/index.html
_site/tags/git/index.html
_site/tags/github/index.html
_site/tags/lean-startup/index.html
_site/tags/ruby/index.html
_site/tags/security/index.html
_site/tags/software-development/index.html
_site/tags/software-quality/index.html
index.html

Hey @mauro-oto,
This PR explains the security hole we found in MP. 
Thanks!

Mercado pago api security vulnerability

---

_layouts/default.html
_site/about.html
_site/assets/css/screen.css
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/git/github/4-useful-github-tricks.html
_site/git/github/how-to-git-push-with-blocked-ports.html
_site/index.html
_site/lean-startup/the-lean-startup-way.html
_site/ruby/benchmark/enumerator-grep-vs-enumerator-select.html
_site/security/mercado-pago-security-vulnerability.html
_site/software-development/software-quality/our-definition-of-done.html
_site/tags/benchmark/index.html
_site/tags/git/index.html
_site/tags/github/index.html
_site/tags/lean-startup/index.html
_site/tags/ruby/index.html
_site/tags/security/index.html
_site/tags/software-development/index.html
_site/tags/software-quality/index.html

Hey @mauro-oto, 
This PR adds a value to head title and fixes issue #25
Thanks!

Fixes head title value

---

_layouts/default.html
_site/about.html
_site/assets/css/screen.css
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/git/github/4-useful-github-tricks.html
_site/git/github/how-to-git-push-with-blocked-ports.html
_site/index.html
_site/lean-startup/the-lean-startup-way.html
_site/ruby/benchmark/enumerator-grep-vs-enumerator-select.html
_site/security/mercado-pago-security-vulnerability.html
_site/software-development/software-quality/our-definition-of-done.html
_site/tags/benchmark/index.html
_site/tags/git/index.html
_site/tags/github/index.html
_site/tags/lean-startup/index.html
_site/tags/ruby/index.html
_site/tags/security/index.html
_site/tags/software-development/index.html
_site/tags/software-quality/index.html

Hey @mauro-oto,
This PR fixes this issue: https://github.com/ombulabs/blog.ombulabs.com/issues/27
Thanks!

Fixes open graph meta tags

---

_includes/author.html
_includes/post_excerpt.html
_includes/post_meta.html
_layouts/page.html
_layouts/post.html
_posts/2015-01-19-4-useful-github-tricks.markdown
_posts/2015-04-09-enumerator-grep-vs-enumerator-select.markdown
_posts/2015-06-18-our-definition-of-done.markdown
_posts/2015-06-28-how-to-git-push-with-blocked-ports.markdown
_site/about.html
_site/assets/css/screen.css
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/git/github/4-useful-github-tricks.html
_site/git/github/how-to-git-push-with-blocked-ports.html
_site/index.html
_site/lean-startup/the-lean-startup-way.html
_site/ruby/benchmark/enumerator-grep-vs-enumerator-select.html
_site/security/mercado-pago-security-vulnerability.html
_site/software-development/software-quality/our-definition-of-done.html
_site/tags/benchmark/index.html
_site/tags/git/index.html
_site/tags/github/index.html
_site/tags/lean-startup/index.html
_site/tags/ruby/index.html
_site/tags/security/index.html
_site/tags/software-development/index.html
_site/tags/software-quality/index.html
assets/css/screen.css
index.html

Hey @mauro-oto,
I’ve refactored the post metadata into a partial. 
Thanks!

Refactor post meta into include

---

_posts/2015-07-20-why-using-default-scope-is-a-bad-idea.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/index.html
_site/rss.xml
_site/ruby/rails/best-practices/why-using-default-scope-is-a-bad-idea.html
_site/tags/best-practices/index.html
_site/tags/rails/index.html
_site/tags/ruby/index.html

Hey @etagwerker,
This PR adds a post with pros/cons of the usage of `default_scope`. 

Why using default scope is a bad idea

---

_posts/2015-07-29-slack-notifications-with-slack-notify.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/index.html
_site/rss.xml
_site/ruby/rails/best-practices/why-using-default-scope-is-a-bad-idea.html
_site/ruby/slack-notifications-with-slack-notify.html
_site/tags/ruby/index.html

Hey @etagwerker, @alanhala, 
This PR adds a new post to the blog, regarding Slack notifications using `slack-notify`. 
Please check it out, any suggestions or comments are welcome. Thanks!

Slack notifications with slack notify

---

_posts/2015-08-04-the-7-days-open-source-challenge.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/git/github/4-useful-github-tricks.html
_site/git/github/how-to-git-push-with-blocked-ports.html
_site/index.html
_site/lean-startup/the-lean-startup-way.html
_site/open-source/the-7-days-open-source-challenge.html
_site/rss.xml
_site/ruby/benchmark/enumerator-grep-vs-enumerator-select.html
_site/ruby/rails/best-practices/why-using-default-scope-is-a-bad-idea.html
_site/ruby/slack-notifications-with-slack-notify.html
_site/security/mercado-pago-security-vulnerability.html
_site/software-development/software-quality/our-definition-of-done.html
_site/tags/open-source/index.html
_site/tags/security/index.html

Hey @mauro-oto @alanhala, 
This is an article about the last talk I gave at the Ruby meetup. 
Thanks!

The 7 days open source challenge

---

_posts/2015-11-19-time-and-material.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/index.html
_site/rss.xml
_site/software-development/time-and-material.html
_site/tags/software-development/index.html

Hey @mauro-oto @schmierkov, 
This post talks about time and material. 
Please check it out and let me know.
Thanks!

Time and material

---

_posts/2015-11-23-how-to-hide-elements-for-protractor-e2e-tests.markdown
_posts/2015-12-09-how-to-hide-elements-for-protractor-e2e-tests.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/index.html
_site/protractor/how-to-hide-elements-for-protractor-e2e-tests.html
_site/rss.xml
_site/tags/protractor/index.html

Hey @schmierkov @mauro-oto,
This PR explains how to interact with hidden elements in Protractor. 
Please check it out and let me know your thoughts. 
Thanks!

Protractor e2e testing with hidden elements

---

_posts/2016-01-20-set-up-and-run-hubot-in-non-heroku-server.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/authors/schmierkov/index.html
_site/hubot/linux/set-up-and-run-hubot-in-non-heroku-server.html
_site/hubot/unix/set-up-and-run-hubot-in-non-heroku-server.html
_site/index.html
_site/rss.xml
_site/tags/hubot/index.html
_site/tags/linux/index.html
_site/tags/unix/index.html

Hey @etagwerker, @schmierkov, 
I wrote an article about deploying Hubot to a non-Heroku server, and how to run it as a service in the background.

Hubot in non heroku server

---

_includes/pagination.html
_site/index.html
_site/page2/index.html

Hey @etagwerker, @schmierkov, 
This PR fixes the blog pagination. 
Fixes https://github.com/ombulabs/blog.ombulabs.com/issues/58.

Fixes pagination links, they were leading to a 404 because of the missing prefix

---

_posts/2016-02-16-ten-steps-to-evaluate-a-rails-project.markdown
_posts/2016-02-17-ten-steps-to-evaluate-a-rails-project.markdown
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/authors/schmierkov/index.html
_site/index.html
_site/page2/index.html
_site/rails/maintenance/ten-steps-to-evaluate-a-rails-project.html
_site/rss.xml
_site/tags/maintenance/index.html
_site/tags/rails/index.html

Hey @mauro-oto @schmierkov, 
I wrote an article about evaluating the quality of a Rails project. 
Please check it out and let me know.
Thanks!

10 simple steps to evaluate a rails project

---

_posts/2016-04-22-session-user-flow.markdown
_site/rss.xml
_site/ruby/rails/sessions/session-user-flow.html

@etagwerker @mauro-oto this fixes the broken code block in the session post

fix code block for session post

---

Gemfile.lock
_posts/2016-04-27-introducing-infractores.markdown
_posts/2016-04-29-introducing-infractores.markdown
_site/Gemfile.lock
_site/authors/etagwerker/index.html
_site/authors/mauro-oto/index.html
_site/authors/schmierkov/index.html
_site/index.html
_site/open-source/crowdsourcing/introducing-infractores.html
_site/page2/index.html
_site/rss.xml
_site/tags/crowdsourcing/index.html
_site/tags/open-source/index.html

Hey @ombulabs/hackers,
I wrote a post about https://github.com/ombulabs/infractores
Thanks!

Introducing infractores

---

_site/assets/js/index.js
assets/js/index.js

Hey @etagwerker, @lubc, 
This PR fixes an error I've noticed in the blog, related to code we're not using which comes from the Kasper theme. 

Fix JS error: $img is undefined

---

_posts/2017-02-13-how-to-run-multiple-dependency-builds-on-your-ci-server.markdown

Hey @etagwerker @mauro-oto , 
This PR adds a new post to the blog about how to run multiple dependency builds. 
Please check it out. Thanks!

Post about multiple dependency builds

---

_posts/2017-04-28-how-to-track-down-a-flaky-test.markdown

Hey @etagwerker, @lubc, 
This PR adds a blog post about random failures in tests. 

A short flaky test story

---

_posts/2015-06-30-the-lean-startup-way.markdown
_site/lean-startup/the-lean-startup-way.html

It's now located at http://www.tutiendaonline.com.ar

Corrected link for vidrieras.in

---

_layouts/default.html

Fix pixelated logo in tweets

---

Gemfile
Gemfile.lock
_plugins/sitemap.rb
spec/blog_spec.rb

Adds test coverage to the blog regeneration, inspired by https://gist.github.com/thbar/10be2ea924b81f78d24ab800461bfee3

Add test coverage

---

_posts/2018-11-12-writing-fast-rails-part-2.markdown
_posts/2018-11-14-writing-fast-rails-part-2.markdown

Re: https://trello.com/c/CVZdIOlG/1-tips-for-writing-fast-rails-part-2
Please check it out. Thanks!

Blogpost - Tips for Writing Fast Rails Part 2

---

.travis.yml
Rakefile
spec/blog_spec.rb

Hey @mauro-oto, 
This PR adds basic config for Travis CI. 
Thanks!

Add Travis CI config file

---

_posts/2019-01-09-tools-we-use.md

Just two questions:
1. Do we still use "Visual Website Optimizer" - "We use [Visual Website Optimizer](https://v2.visualwebsiteoptimizer.com) to create AB tests."
2. Do we still use "CodeClimate" - We use [CodeClimate](https://codeclimate.com) to monitor code quality.

"Tools We Use at Ombu Labs"

---

_includes/tag_list.html

This PR fixes issue #163192859.

Allow ads on all articles

---

_posts/2019-02-19-refactoring-state-pattern.markdown
_posts/2019-02-20-refactoring-state-pattern.markdown

Hey @lubc @ercohen14 
This is my new post for the blog.
Please, take a look. Thanks!

Post: Refactoring with Design Patterns - The State Pattern

---

_posts/2019-02-27-stripe-connect-part-1.md
_posts/2019-02-28-stripe-connect-part-1.md

Hey @ercohen14 @cleicar  
This PR adds a new article for the blog. Please take a look. Thanks!

blogpost/Stripe Connect

---

_includes/sidebar.html

This PR fix the problem with adblock.
I've changed the class name from 'ad' to 'adv'.

Changed ad class name to avoid being blocked by adblock

---

_posts/2019-03-13-activeadmin-vs-administrate.md
_posts/2019-03-18-activeadmin-vs-administrate.md

New blog post on ActiveAdmin vs Administrate gems

Post on administrative gems

---

_posts/2019-03-19-processing-a-csv-file-in-batch-with-sidekiq.markdown
_posts/2019-04-03-processing-a-csv-file-in-batch-with-sidekiq.markdown

Hey guys!
This is my new article for Ombu Labs blog.
Please, take a look. 
Thanks.

Blog Post: Processing a CSV file in batch with Sidekiq

---

_includes/sidebar.html

Story: https://www.pivotaltracker.com/story/show/166330822
This PR goes with PR: https://github.com/ombulabs/ombulabs.com/pull/162

Edit ad html

---

_posts/2019-06-26-contribute-open-source.markdown
_posts/2019-06-3-4-contribute-open-source.markdown

Raw post about contributing to open source(will update description accordingly)

Contributing to open source blog post

---

_posts/2019-07-16-gentle-intro-to-docker.markdown
_posts/2019-07-18-gentle-intro-to-docker.markdown

The first in a series of basic Docker tutorials

Gentle introduction to Docker

---

_posts/2019-10-4-manual-testing-how-to-become-a-better-tester-of-your-own-code.markdown

Text updated according to Luis' comments here. https://github.com/ombulabs/blog/pull/202/files/1fefb9fd5189c6addef9a780a8bb9c32f50deb02
@bronzdoc could you please review? Thank you!
@etagwerker @lubc would love your feedback too.

Updating according to Luis' feedback.

---

_posts/2019-11-27-making-your-clients-better-product-owners.markdown

@etagwerker @lubc @bronzdoc would appreciate your feedback :)

New blog post on clients as product owners. Ready for review

---

_posts/2019-11-27-making-your-clients-better-product-owners.markdown
_posts/2019-12-10-onboarding-with-slack-workflows.markdown
_posts/2019-12-12-onboarding-with-slack-workflows.markdown

@bronzdoc @cleicar @etagwerker would appreciate your feedback :)

New blog post on onboarding new team members with Slack workflows

---

_posts/2020-01-28-Tips-for-creating-open-source-projects-that-are-contributor-friendly.markdown

Tips for creating open source projects that are contributor-friendly post, still thinking if i should add more,  reviews are appreciated

Tips for creating open source projects that are contributor-friendly

---

_includes/author.html
_includes/disqus.html
_includes/pagination.html
_includes/post_meta.html
_includes/share.html
_includes/sidebar.html
_includes/site_footer.html
_includes/tag_list.html
_layouts/author_index.html
_layouts/category_index.html
_layouts/default.html
_layouts/post.html

Pivotal ticket reference: https://www.pivotaltracker.com/story/show/170953174
This PR:
- Improves accessibility for Screen Readers adding landmarks, aria attributes, etc.

[#170953174] Make OmbuLabs blog accessible: screen reader compatibility

---

CODE_OF_CONDUCT.md
README.md

Hey @bronzdoc, 
This PR adds Contributor Covenant 2.0 to our project. 
Thanks!

Add code of conduct for blog project

---

assets/js/index.js

Pivotal story reference: https://www.pivotaltracker.com/story/show/171915746
This PR:
- Changes the selector on js file to make close button work again.

[#171915746] Ad inside blog is NOT closing as expected 

---

_posts/2020-04-01-method-s-arguments-pt-1.markdown

My PR for part2 included the part1 file so I took the feedback ernesto gave on that file and moved to a new PR.

Add Ernesto's suggestions to Method Arguments Part 1

---

_posts/2020-04-15-methods-arguments-ruby-part2.markdown

Just a small typo fix (- positionals, + position)

Method Arguments Part 2: There's a typo on the last section.

---

_config.yml
_posts/2020-04-16-remote-junior-developer-tips.markdown

This is my first blog post, so I'm hoping I formatted correctly. I wasn't sure how to do sub headings? Comment welcome.

Post Junior Developer Tips

---

_posts/2020-05-08-coupling-and-cohesion.markdown
_posts/2020-05-19-coupling-and-cohesion.markdown

This is my post on coupling and cohesion....

New post on coupling and cohesion

---

_posts/2020-07-20-understanding-bundler.markdown
_posts/2020-07-29-understanding-bundler.markdown

**IMPORTANT: blog posts must be approved by two reviewers before they can be published, one of which must be a native English speaker.**
Blogpost about how Bundler works, what does `bundle exec` do, and how Ruby, Rubygems and RVM do some related things.

Blog post on how Bundler works

---

_posts/2020-07-29-understanding-bundler.markdown

**IMPORTANT: blog posts must be approved by two reviewers before they can be published, one of which must be a native English speaker.**
Fix a few typos on my latest blogpost

Fix typos for Understanding Bundler blogpost

---

_posts/2020-07-13-our-code-review-etiquette.md
_posts/2020-08-05-our-code-review-etiquette.md

**IMPORTANT: blog posts must be approved by two reviewers before they can be published, one of which must be a native English speaker.**
Hey guys, this is my new blog post. 
It was mostly extracted from our code review guide: https://github.com/ombulabs/guides/wiki/13.-Code-Review-Guide
Please, take a look. Thanks!

[Post] Our code review etiquette

---

_posts/2020-08-07-snap-minis.markdown

Hey @ABizzinotto, 
I noticed a couple of things that could be improved and updated your article: 
- Title should say Snapchat (not SnapChat)
- Video should be embedded (not linked)
Please check it out. 
Thanks!

Update a few details about Snapchat's brand

---

_posts/2020-03-19-our-values.markdown

Hey, 
This PR adds ids to the headings of the our values blog post. 
It will make it easier to share sections of this page in Tettra and other places. Also, it fixes https://github.com/ombulabs/blog/issues/438
Thanks!

Our values: Update headings so that they can be shared from other places 

---

README.md
_posts/2015-08-04-the-7-days-open-source-challenge.markdown
_posts/2016-02-04-ombulabs-products.markdown
_posts/2016-02-17-ten-steps-to-evaluate-a-rails-project.markdown
_posts/2016-04-15-our-hiring-process.markdown
_posts/2016-05-10-joys-and-woes-of-pair-programming.markdown
_posts/2016-05-16-dry-your-test-unit.markdown
_posts/2016-07-04-standard-getting-started.md
_posts/2017-06-07-announcing-fastruby-io-productized-rails-upgrades.md
_posts/2017-08-22-how-we-helped-predictable-revenue-scale.md
_posts/2018-06-01-another-successful-rails-girls-event.markdown
_posts/2018-07-23-performance-improvements-using-derailed-benchmarks.markdown
_posts/2018-09-06-how-we-use-pivotal-tracker-at-ombu-labs.markdown
_posts/2018-09-12-fastruby-io-exit-calls.markdown
_posts/2018-11-27-kickoff-calls.markdown
_posts/2019-01-09-tools-we-use.md
_posts/2019-02-05-gcal-for-project-management.md
_posts/2019-02-13-three-useful-data-migrations-patterns-in-rails.markdown
_posts/2019-02-28-stripe-connect-part-1.md
_posts/2019-03-08-the-importance-of-sprint-retrospectives.md
_posts/2019-04-03-processing-a-csv-file-in-batch-with-sidekiq.markdown
_posts/2019-04-18-submitting-prs.markdown
_posts/2019-07-02-heroku-review-apps-in-multi-tenant-application.markdown
_posts/2019-07-11-working-remotely-team.markdown
_posts/2019-08-23-bitrix-rails-integration.markdown
_posts/2019-09-04-service-objects.markdown
_posts/2020-01-28-Tips-for-creating-open-source-projects-that-are-contributor-friendly.markdown
_posts/2020-03-19-our-values.markdown
index.html
spec/blog_spec.rb

**What is this PR:**
**Description:**
Branding should be consistent with our own company name. 😄 
This is following the style guide (http://ombulabs.github.io/styleguide/)
**Related story:**
See: https://www.pivotaltracker.com/story/show/175108442
**How has this been tested?**
**What manual tests have been run?**
Check that things are fixed in one of the articles listed below.
**What browsers did you test it on (if applicable)?**
**What devices did you test it on (if applicable)?**

Rename Ombu Labs as OmbuLabs

---

_posts/2020-09-15-open-sourcing-a-private-project.markdown

Hello,
This blog post is about moving projects from private to open source. Maybe it could use a better title? I would like to have @manuca review since he just did this process.
Thanks!

Add blog post on moving private projects to open source

---

_posts/2020-10-21-points-blind-estimation-tool.markdown

@lubc here I am adding a link to Points from the new blog post.

Adds a link to points

---

_posts/2020-12-10-webpack-vs-sprockets.markdown
_posts/2020-12-23-webpack-vs-sprockets.markdown

**IMPORTANT: blog posts must be approved by two reviewers before they can be published, one of which must be a native English speaker.**
[Add any information about this post here. Leave the note above when opening the Pull Request.]

Blogpost comparing Webpack and Sprockets
